= Variables



Variables are names we give to some values to help us deal with data.

In the example `pi = 3.14`, the name `pi` is connected to the value `3.14`.
From our experience, we can tell that the type of a variable `pi` is a (decimal) number.

Another example would be `firstName = Alice`, where `firstName` is the name of a variable with the value `Alice`.
We would say that the type of this variable is a word.

Variables in programming languages work similarly.
They have their name, value, and type.




== Variable declaration


Nim is a https://en.wikipedia.org/wiki/Type_system#STATIC[statically typed] programming language, meaning the variables and their type need to be declared before using them.

We can declare a variable using `var` keyword, just by stating its name and type (the value can be added later) by using this syntax:
[source]
----
var <name>: type
----

If we already know its value, we can declare a variable and give it a value immediately:
[source]
----
var <name>: <type> = <value>
----

Nim also has https://en.wikipedia.org/wiki/Type_inference[type inference] ability -- compiler can automatically detect the type of a variable from its value, without explicitly stating the type.
(More about various types in the next section.)

We can do that like this:
[source]
----
var <name> = <value>
----


An example in Nim looks like this:
[source]
----
var a: int  # <1>
var b = 7   # <2>
----
<1> Variable `a` is of type `int` (integer) with no value explicitly set.
<2> Variable `b` has a value of `7` -- its type is automatically detected as integer.


Instead of typing `var` for each variable, multiple variables (not necessary of the same type) can be declared in the same `var` block.
In Nim, blocks are parts of code with the same indentation (same number of spaces before the first character), and the default indentation level is two spaces.

[source]
----
var
  c = -11
  d = "Hello"
  e = '!'
----

NOTE: In Nim tabs are not allowed as indentations. +
You can set up your code editor to convert pressing `Tab` to any number of spaces. +
In VS Code, the default setting is to convert `Tab` to four spaces. This is easily overridden in settings (`Ctrl+,`) by setting `"editor.tabSize": 2`.

{nbsp}

Variables are mutable, i.e. their value can change (multiple times), but their type must stay the same as declared.

[source]
----
var f = 7           <1>

f = -3              <2>
f = 19
f = "Hello" # error <3><4>
----
<1> Variable `f` has an initial value of `7` and its type is inferred as `int`.
<2> The value of `f` is first changed to `-3`, and then to `19`. Both of these are integers, the same as the original value.
<3> Trying to change the value of `f` to `"Hello"` produces an error because `Hello` is not a number, and this would change the type of `f` from an integer to a string.
<4> `# error` is a comment. Comments in Nim code are written after `#` character -- everything after it in the same line will be ignored.




== Immutable variables

Unlike variables declared with `var` keyword, two more types of variables exist in Nim, whose value cannot change, one declared with `const` keyword, and the other declared with `let` keyword.



=== Const

The value of an immutable variable declared with `const` keyword must be known at compile time (before the program is run).

For example, we can declare the acceleration of gravity as `const g = 9.81` or pi as `const pi = 3.14`, as we know their values in advance and these values will not change during the execution of our program.

[source]
----
const g = 35
g = -27         # error <1>

var h = -5
const i = h + 7 # error <2>
----
<1> The value of a constant cannot be changed.
<2> Variable `h` is not evaluated at compile time (it is a variable and its value can change during the execution of a program), consequently the value of constant `i` is also not known at compile time, and this will raise an error.

In some programming languages it is a common practice to have the names of constants written in `ALL_CAPS`.
Constants in Nim are written just like any other variable (lowercase letters), and if a name consists of more than one word the usual way is to write it in `camelCase` style. (Notice that the first letter in a name should be lowercase.)



=== Let

Immutable values declared with `let` don't need to be known at compile time, their values can be set at any time during the execution of a program, but once it is set, their value cannot change.

[source]
----
let j = 35
j = -27 # error <1>

var k = -5
let l = k + 7   <2>
----
<1> The value of an immutable cannot be changed.
<2> In contrast to `const` example above, this works.

In practice, you will see/use `let` more frequently than `const`.




// == Exercises

// 1. Create an immutable variable containing your name. Print it on the screen.
