= Interacting with user input



Using the stuff we introduced so far (basic data types and containers, control flow, loops) allows us to make quite a few simple programs.
To make our programs more interactive, we need an option to read data from a file, or ask a user for an input.




== Reading from a file

Let's say we have a text file called `people.txt` in the same directory as our Nim code.
The contents of that file look like this:

[source]
.people.txt
----
include::{source-dir}/people.txt[]

----

We want to use the contents of that file in our program, as a list (sequence) of names.

[source]
.readFromFile.nim
----
include::{source-dir}/readFromFile.nim[]
----
<1> To read contents of a file, we use `readFile` function, and we provide a path to the file from which to read (if the file is in the same directory as our Nim program, providing a filename is enough). The result is a multiline string.
<2> To split a multiline string into a sequence of strings (each string contains all the contents of a single line) we use `splitLines` from `strutils` module.

[source, output]
----
Alice A.
Bob B.
Carol C.
            <1>
@["Alice A.", "Bob B.", "Carol C.", ""] <2>
----
<1> There was a final new line (empty last line) in the original file, which is also present here.
<2> Because of the final new line, our sequence is longer than we expected/wanted.

To solve the problem of a final new line, we can use `strip` function from `strutils` after we have read from a file.

[source]
.readFromFile2.nim
----
include::{source-dir}/readFromFile2.nim[]
----
<1> Using `strip` provides the expected results.

[source, output]
----
Alice A.
Bob B.
Carol C.
@["Alice A.", "Bob B.", "Carol C."]
----




== Reading user input

If we want to interact with a user, we must be able to ask them for an input, and then process it and use it.
We need to read from https://en.wikipedia.org/wiki/Standard_streams#Standard_input_(stdin)[standard input (stdin)] by passing `stdin` to `readLine` function.

[source]
.interaction1.nim
----
include::{source-dir}/interaction1.nim[]
----
<1> Type of `name` is inferred to be a string.


[source, output]
----
Please enter your name:
        <1>
----
<1> Waiting for a user input. After we write our name and press `Enter`, the program will continue.

[source, output]
----
Please enter your name:
Alice
Hello Alice, nice to meet you!
----

NOTE: VS Code users cannot run this the usual way (using `Ctrl+Alt+N`) because output window doesn't allow user inputs. This needs to be run in the terminal.




== Dealing with numbers

Reading from a file or from a user input always gives a string as a result.
If we would like to use numbers, we need to convert strings to numbers -- we use `strutils` module and we convert to integers using `parseInt` or we convert to floats using `parseFloat` function.

[source]
.interaction2.nim
----
include::{source-dir}/interaction2.nim[]
----
<1> Convert a string to an integer.

[source, output]
----
Please enter your year of birth:
1934
You are 84 years old.
----

{nbsp}

If we have file `numbers.txt` in the same directory as our Nim code, with the following content:

[source]
.numbers.txt
----
include::{source-dir}/numbers.txt[]
----

We want to read that file and find the sum and average of the numbers provided.

[source]
.interaction3.nim
----
include::{source-dir}/interaction3.nim[]
----
<1> We import multiple modules. `strutils` gives us `strip` and `splitLines`, `sequtils` gives `map`, and `math` gives `sum`.
<2> We strip the final new line, and split lines to create a sequence of strings.
<3> `map` works by applying a function (in this case `parseFloat`) to the each member of a container. In other words, we convert each string to a float.
<4> Using `sum` from `math` module to give us the sum of all elements of a sequence.
<5> We need to convert the length of a sequence to float, because `sumNums` is a float.

[source, output]
----
226.15
45.23
----




== Exercises

1. Ask a user for their height and weight. Calculate their https://en.wikipedia.org/wiki/Body_mass_index[BMI]. Report them the BMI value and the category.

2. Repeat <<_exercises_4, Collatz conjecture exercise>> so your program asks a user for a starting number. Print the resulting sequence.

3. Ask a user for a string they want to have it reversed. Create a procedure which takes a string and returns a reversed version. For example, if user types `Nim-lang`, the procedure should return `gnal-miN`. (Hint: use indexing and `countdown`)